-- TASK 14
-- Görev 14: Veritabanındaki tüm Primary Key ve Foreign Key'leri listeleyin.

SELECT CONSTRAINT_SCHEMA, TABLE_NAME, CONSTRAINT_NAME 
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
ORDER BY CONSTRAINT_SCHEMA, TABLE_NAME, CONSTRAINT_NAME;

