-- TASK 14
-- Görev 14: Veritabanındaki tüm Primary Key ve Foreign Key'leri listeleyin.

SELECT CONSTRAINT_SCHEMA, TABLE_NAME, CONSTRAINT_NAME 
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
-- WHERE CONSTRAINT_SCHEMA = 'HumanResources' 
-- WHERE CONSTRAINT_NAME LIKE 'UQ%'
ORDER BY CONSTRAINT_SCHEMA, TABLE_NAME, CONSTRAINT_NAME;


SELECT * -- CONSTRAINT_SCHEMA, TABLE_NAME, CONSTRAINT_NAME 
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
-- WHERE CONSTRAINT_SCHEMA = 'HumanResources' 
ORDER BY CONSTRAINT_SCHEMA, TABLE_NAME, CONSTRAINT_NAME;


SELECT * 
FROM sys.foreign_key_columns

SELECT *
FROM sys.key_constraints;   

SELECT businessEntityID [ID], FirstName, LastName FROM Person.Person where businessEntityID = 20684