-- TASK13
-- Görev 13: Veritabanında bulunan tüm tabloları ve 
-- her tablonun sütunlarını listeleyin.

SELECT tbl.TABLE_SCHEMA, tbl.TABLE_NAME, col.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLES tbl 
LEFT JOIN INFORMATION_SCHEMA.COLUMNS col ON col.TABLE_NAME = tbl.TABLE_NAME AND col.TABLE_SCHEMA = tbl.TABLE_SCHEMA
WHERE tbl.TABLE_TYPE = 'BASE TABLE'
ORDER BY tbl.TABLE_SCHEMA, tbl.TABLE_NAME, col.ORDINAL_POSITION
;

--
SELECT tbl.TABLE_SCHEMA, tbl.TABLE_NAME, STRING_AGG(col.COLUMN_NAME, ', ') [Columns]
FROM INFORMATION_SCHEMA.TABLES tbl 
LEFT JOIN INFORMATION_SCHEMA.COLUMNS col ON col.TABLE_NAME = tbl.TABLE_NAME 
                                            AND col.TABLE_SCHEMA = tbl.TABLE_SCHEMA
WHERE tbl.TABLE_TYPE = 'BASE TABLE'
GROUP BY tbl.TABLE_SCHEMA, tbl.TABLE_NAME
ORDER BY tbl.TABLE_SCHEMA, tbl.TABLE_NAME
;